add prototype file
maximumJavascript/js-notes-md pull request #8
Opened 2021-12-21 15:12 UTC by rogedkone

Create test pull request

2021-12-23 17:02 UTC, maximumJavascript requested changes

2021-12-23 17:02 UTC, maximumJavascript commented on prototype.md
> +Прототипы всем нужны для наследования
дополнить статью, указать ссылку на другую статью в формате obsidian.md

2021-12-24 14:38 UTC, rogedkone commented
add GorvoStory

2021-12-24 14:45 UTC, rogedkone commented
add links

2021-12-24 15:04 UTC, closed without merging