add new file
maximumJavascript/js-notes-md pull request #9
Opened 2021-12-24 11:46 UTC by RomanAgF

add Logic_operators.md file to develop branch

2021-12-24 13:40 UTC, maximumJavascript requested changes

2021-12-24 13:40 UTC, maximumJavascript commented on Логические связки И ИЛИ.md
> +[[Объекты, общее]]
насколько объекты вязаны с этой статьей?) есть более релевантные, и даже можно несколько ссылок дать

2021-12-24 13:40 UTC, maximumJavascript commented on Логические связки И ИЛИ.md
> +|| true false
погугли как в маркдауне сделать табличку
раз ты ее хотел сделать

2021-12-25 13:01 UTC, RomanAgF commented on Логические связки И ИЛИ.md
> +|| true false
изменил

2021-12-25 13:03 UTC, RomanAgF commented on Логические связки И ИЛИ.md
> +|| true false
вроде получилось я на самом деле не хотел табличку но с ней нагляднее)

2021-12-25 15:21 UTC, merged